### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by excentris** [spotify/apollo#242]
I'd like to submit a patch but I am unable to build the project in order to test it.
I've cloned the project and run `mvn package`, but I get this:

```
16:13 $ mvn package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-bom:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-core:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-api:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-api:[unknown-version], /Users/eduardo/Development/apollo/apollo-api/pom.xml, line 81, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-api-impl:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-environment:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-meta:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-route:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-test:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-extra:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-extra:[unknown-version], /Users/eduardo/Development/apollo/apollo-extra/pom.xml, line 92, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-entity:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-http-service:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-slack:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-jetty-http-server:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-jetty-http-server:[unknown-version], /Users/eduardo/Development/apollo/modules/jetty-http-server/pom.xml, line 103, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-okhttp-client:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-metrics:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ com.spotify:apollo-parent:2.0.0-SNAPSHOT, /Users/eduardo/Development/apollo/pom.xml, line 123, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.spotify:apollo-parent:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 123, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Spotify Apollo Parent
[INFO] Spotify Apollo Bill of Materials
[INFO] Spotify Apollo Service Core (aka Leto)
[INFO] Spotify Apollo API Interfaces
[INFO] Spotify Apollo Route
[INFO] Spotify Apollo API Implementations
[INFO] Spotify Apollo Metadata
[INFO] Spotify Apollo API Environment
[INFO] Spotify Apollo Extra
[INFO] Spotify Apollo okhttp Client Module
[INFO] Spotify Apollo Metrics Module
[INFO] Spotify Apollo Testing Helpers
[INFO] Spotify Apollo Entity Middleware
[INFO] Spotify Apollo Jetty HTTP Server Module
[INFO] Spotify Apollo HTTP Service
[INFO] Spotify Apollo Slack Module
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Spotify Apollo Parent 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ apollo-parent ---
[INFO] 
[INFO] --- license-maven-plugin:1.8:check-file-header (check-file-header) @ apollo-parent ---
[WARNING] No file to scan.
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Spotify Apollo Bill of Materials 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ apollo-bom ---
[INFO] 
[INFO] --- license-maven-plugin:1.8:check-file-header (check-file-header) @ apollo-bom ---
[WARNING] No file to scan.
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Spotify Apollo Service Core (aka Leto) 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ apollo-core ---
[INFO] 
[INFO] --- license-maven-plugin:1.8:check-file-header (check-file-header) @ apollo-core ---
[INFO] Will search files to update from root /Users/eduardo/Development/apollo/apollo-core/src/main/java
[INFO] Will search files to update from root /Users/eduardo/Development/apollo/apollo-core/src/test/java
[INFO] Scan 13 files header done in 36,35ms.
[INFO] All files are up-to-date.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ apollo-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ apollo-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ apollo-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ apollo-core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ apollo-core ---
[INFO] Surefire report directory: /Users/eduardo/Development/apollo/apollo-core/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.spotify.apollo.core.ServicesTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/Users/eduardo/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.256 sec
Running com.spotify.apollo.core.ServiceImplTest
Jan 25, 2018 4:13:29 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.RuntimeException: Fail foobar
java.lang.RuntimeException: Fail foobar
        at com.spotify.apollo.core.ServiceImplTest$1.configure(ServiceImplTest.java:506)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.spotify.apollo.core.ServiceImpl.initInstance(ServiceImpl.java:196)
        at com.spotify.apollo.core.ServiceImpl.start(ServiceImpl.java:148)
        at com.spotify.apollo.core.ServiceImpl.start(ServiceImpl.java:112)
        at com.spotify.apollo.core.ServiceImpl.start(ServiceImpl.java:107)
        at com.spotify.apollo.core.ServiceImplTest.testExceptionDuringInit(ServiceImplTest.java:517)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:844)

Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.554 sec

Results :

Tests run: 45, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ apollo-core ---
[INFO] Building jar: /Users/eduardo/Development/apollo/apollo-core/target/apollo-core-2.0.0-SNAPSHOT.jar
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Spotify Apollo API Interfaces 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ apollo-api ---
[INFO] 
[INFO] --- license-maven-plugin:1.8:check-file-header (check-file-header) @ apollo-api ---
[INFO] Will search files to update from root /Users/eduardo/Development/apollo/apollo-api/src/main/java
[INFO] Will search files to update from root /Users/eduardo/Development/apollo/apollo-api/src/test/java
[INFO]  - ignore file (detected %%Ignore-License) /Users/eduardo/Development/apollo/apollo-api/src/main/java/com/spotify/apollo/QueryStringDecoder.java
[INFO] Scan 36 files header done in 40,676ms.
[INFO] 
 * uptodate header on 35 files.
 * ignore header on 1 file.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ apollo-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/eduardo/Development/apollo/apollo-api/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ apollo-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /Users/eduardo/Development/apollo/apollo-api/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spotify Apollo Parent .............................. SUCCESS [  0.968 s]
[INFO] Spotify Apollo Bill of Materials ................... SUCCESS [  0.009 s]
[INFO] Spotify Apollo Service Core (aka Leto) ............. SUCCESS [  1.971 s]
[INFO] Spotify Apollo API Interfaces ...................... FAILURE [  0.955 s]
[INFO] Spotify Apollo Route ............................... SKIPPED
[INFO] Spotify Apollo API Implementations ................. SKIPPED
[INFO] Spotify Apollo Metadata ............................ SKIPPED
[INFO] Spotify Apollo API Environment ..................... SKIPPED
[INFO] Spotify Apollo Extra ............................... SKIPPED
[INFO] Spotify Apollo okhttp Client Module ................ SKIPPED
[INFO] Spotify Apollo Metrics Module ...................... SKIPPED
[INFO] Spotify Apollo Testing Helpers ..................... SKIPPED
[INFO] Spotify Apollo Entity Middleware ................... SKIPPED
[INFO] Spotify Apollo Jetty HTTP Server Module ............ SKIPPED
[INFO] Spotify Apollo HTTP Service ........................ SKIPPED
[INFO] Spotify Apollo Slack Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.218 s
[INFO] Finished at: 2018-01-25T16:13:30+01:00
[INFO] Final Memory: 28M/93M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project apollo-api: Fatal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apollo-api
```

**Comment by jhaals** [comment]
Hi! Are you trying to build the 1.x branch or master? Master is confusingly not the active branch for this project.

**Comment by excentris** [comment]
I was trying to build master. Should I be trying to build 1.x?

**Comment by excentris** [comment]
On branch 1.x I get the same error...

**Comment by excentris** [comment]
I found out what the problem was. I am using [jenv](https://github.com/gcuisinier/jenv) to manage different java versions and maven was using java 9 instead of 8. Getting maven to use java 8 solved the problem.
